# Generated by Django 5.2.6 on 2026-09-05 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. Home, Office', max_length=100, verbose_name='Title')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('country', models.CharField(default='Iran', max_length=100, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province/State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address_line', models.CharField(max_length=255, verbose_name='Address Line')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
