# Generated by Django 5.2.6 on 2026-08-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
