/**
 * Iranian Provinces and Cities Dataset
 * Covers all 31 provinces and their major cities/shahrestans.
 */

export const IRAN_PROVINCES = [
  { id: "Tehran", name: "Tehran (تهران)" },
  { id: "Isfahan", name: "Isfahan (اصفهان)" },
  { id: "Fars", name: "Fars (فارس)" },
  { id: "Khorasan Razavi", name: "Khorasan Razavi (خراسان رضوی)" },
  { id: "East Azerbaijan", name: "East Azerbaijan (آذربایجان شرقی)" },
  { id: "West Azerbaijan", name: "West Azerbaijan (آذربایجان غربی)" },
  { id: "Mazandaran", name: "Mazandaran (مازندران)" },
  { id: "Gilan", name: "Gilan (گیلان)" },
  { id: "Khuzestan", name: "Khuzestan (خوزستان)" },
  { id: "Kermanshah", name: "Kermanshah (کرمانشاه)" },
  { id: "Alborz", name: "Alborz (البرز)" },
  { id: "Qom", name: "Qom (قم)" },
  { id: "Markazi", name: "Markazi (مرکزی)" },
  { id: "Qazvin", name: "Qazvin (قزوین)" },
  { id: "Zanjan", name: "Zanjan (زنجان)" },
  { id: "Yazd", name: "Yazd (یزد)" },
  { id: "Kerman", name: "Kerman (کرمان)" },
  { id: "Hamadan", name: "Hamadan (همدان)" },
  { id: "Lorestan", name: "Lorestan (لرستان)" },
  { id: "Golestan", name: "Golestan (گلستان)" },
  { id: "Hormozgan", name: "Hormozgan (هرمزگان)" },
  { id: "Bushehr", name: "Bushehr (بوشهر)" },
  { id: "Ardabil", name: "Ardabil (اردبیل)" },
  { id: "Kurdistan", name: "Kurdistan (کردستان)" },
  { id: "Sistan and Baluchestan", name: "Sistan and Baluchestan (سیستان و بلوچستان)" },
  { id: "Semnan", name: "Semnan (سمنان)" },
  { id: "Chaharmahal and Bakhtiari", name: "Chaharmahal and Bakhtiari (چهارمحال و بختیاری)" },
  { id: "Kohgiluyeh and Boyer-Ahmad", name: "Kohgiluyeh and Boyer-Ahmad (کهگیلویه و بویراحمد)" },
  { id: "North Khorasan", name: "North Khorasan (خراسان شمالی)" },
  { id: "South Khorasan", name: "South Khorasan (خراسان جنوبی)" },
  { id: "Ilam", name: "Ilam (ایلام)" },
];

export const IRAN_CITIES_BY_PROVINCE = {
  Tehran: [
    "Tehran (تهران)",
    "Shemiranat (شمیرانات)",
    "Rey (ری)",
    "Pardis (پردیس)",
    "Shahriar (شهریار)",
    "Varamin (ورامین)",
    "Eslamshahr (اسلامشهر)",
    "Qods (قدس)",
    "Malard (ملارد)",
    "Damavand (دماوند)",
    "Pakdasht (پاکدشت)",
    "Robat Karim (رباط کریم)",
    "Firuzkuh (فیروزکوه)",
    "Bumehen (بومهن)",
    "Rudehen (رودهن)",
  ],
  Isfahan: [
    "Isfahan (اصفهان)",
    "Kashan (کاشان)",
    "Najafabad (نجف‌آباد)",
    "Shahin Shahr (شاهین‌شهر)",
    "Khomeyni Shahr (خمینی‌شهر)",
    "Lenjan (لنجان)",
    "Falavarjan (فلاورجان)",
    "Mobarakeh (مبارکه)",
    "Shahreza (شهرضا)",
    "Golpayegan (گلپایگان)",
    "Natanz (نطنز)",
    "Na'in (نائین)",
    "Aran va Bidgol (آران و بیدگل)",
    "Semirom (سمیرم)",
  ],
  Fars: [
    "Shiraz (شیراز)",
    "Marvdasht (مرودشت)",
    "Jahrom (جهرم)",
    "Fasa (فسا)",
    "Kazerun (کازرون)",
    "Lar (لار)",
    "Abadeh (آباده)",
    "Darab (داراب)",
    "Firuzabad (فیروزآباد)",
    "Noorabad (نورآباد)",
    "Neyriz (نی‌ریز)",
    "Eqbaliyeh (اقلید)",
    "Gerash (گراش)",
    "Lamerd (لامرد)",
  ],
  "Khorasan Razavi": [
    "Mashhad (مشهد)",
    "Neyshabur (نیشابور)",
    "Sabzevar (سبزوار)",
    "Torbat-e Heydarieh (تربت حیدریه)",
    "Quchan (قوچان)",
    "Kashmar (کاشمر)",
    "Chenaran (چناران)",
    "Torbat-e Jam (تربت جام)",
    "Taybad (تایباد)",
    "Gonabad (گناباد)",
    "Sarakhs (سرخس)",
    "Fariman (فریمان)",
    "Golbahar (گلبهار)",
  ],
  "East Azerbaijan": [
    "Tabriz (تبریز)",
    "Maragheh (مراغه)",
    "Marand (مرند)",
    "Mianeh (میانه)",
    "Ahar (اهر)",
    "Bonab (بناب)",
    "Shabestar (شبستر)",
    "Sarab (سراب)",
    "Azarshahr (آذرشهر)",
    "Malekan (ملکان)",
    "Osku (اسکو)",
    "Jolfa (جلفا)",
    "Sahand (سهند)",
  ],
  "West Azerbaijan": [
    "Urmia (ارومیه)",
    "Khoy (خوی)",
    "Bukan (بوکان)",
    "Mahabad (مهاباد)",
    "Miandoab (میاندوآب)",
    "Salmas (سلماس)",
    "Piranshahr (پیرانشهر)",
    "Naghadeh (نقده)",
    "Maku (ماکو)",
    "Sardasht (سردشت)",
    "Shahin Dezh (شاهین‌دژ)",
    "Takab (تکاب)",
    "Oshnavieh (اشنویه)",
  ],
  Mazandaran: [
    "Sari (ساری)",
    "Babol (بابل)",
    "Amol (آمل)",
    "Qaem Shahr (قائم‌شهر)",
    "Tonekabon (تنکابن)",
    "Noshahr (نوشهر)",
    "Ramsar (رامسر)",
    "Chalus (چالوس)",
    "Behshahr (بهشهر)",
    "Babolsar (بابلسر)",
    "Mahmudabad (محمودآباد)",
    "Fereydunkenar (فریدونکنار)",
    "Nur (نور)",
    "Neka (نکا)",
  ],
  Gilan: [
    "Rasht (رشت)",
    "Bandar-e Anzali (بندر انزلی)",
    "Lahijan (لاهیجان)",
    "Langarud (لنگرود)",
    "Talesh (تالش)",
    "Astara (آستارا)",
    "Someh Sara (صومعه‌سرا)",
    "Fuman (فومن)",
    "Rudsar (رودسر)",
    "Astaneh-ye Ashrafiyeh (آستانه اشرفیه)",
    "Rudbar (رودبار)",
    "Masal (ماسال)",
  ],
  Khuzestan: [
    "Ahvaz (اهواز)",
    "Abadan (آبادان)",
    "Khorramshahr (خرمشهر)",
    "Dezful (دزفول)",
    "Mahshahr (ماهشهر)",
    "Behbahan (بهبهان)",
    "Andimeshk (اندیمشک)",
    "Shush (شوش)",
    "Shushtar (شوشتر)",
    "Izeh (ایذه)",
    "Masjed Soleyman (مسجد سلیمان)",
    "Omidiyeh (امیدیه)",
    "Ramhormoz (رامهرمز)",
  ],
  Kermanshah: [
    "Kermanshah (کرمانشاه)",
    "Eslamabad-e Gharb (اسلام‌آباد غرب)",
    "Javanrud (جوانرود)",
    "Kangavar (کنگاور)",
    "Harsin (هرسین)",
    "Sahneh (صحنه)",
    "Paveh (پاوه)",
    "Sarpol-e Zahab (سرپل ذهاب)",
    "Sonqor (سنقر)",
    "Ravansar (روانسر)",
    "Gilan-e Gharb (گیلانغرب)",
  ],
  Alborz: [
    "Karaj (کرج)",
    "Fardis (فردیس)",
    "Kamal Shahr (کمال‌شهر)",
    "Nazarabad (نظرآباد)",
    "Mohammadshahr (محمدشهر)",
    "Hashtgerd (هشتگرد)",
    "Eshtehard (اشتهارد)",
    "Mahdasht (ماهدشت)",
    "Meshkin Dasht (مشکین‌دشت)",
    "Taleqan (طالقان)",
  ],
  Qom: [
    "Qom (قم)",
    "Qanavat (قنوات)",
    "Jafariyeh (جعفریه)",
    "Kahak (کهک)",
    "Dastjerd (دستجرد)",
    "Salafchegan (سلفچگان)",
  ],
  Markazi: [
    "Arak (اراک)",
    "Saveh (ساوه)",
    "Khomein (خمین)",
    "Mahallat (محلات)",
    "Delijan (دلیجان)",
    "Shazand (شازند)",
    "Tafresh (تفرش)",
    "Ashtian (آشتیان)",
    "Zarandieh (زرندیه)",
    "Komijan (کمیجان)",
  ],
  Qazvin: [
    "Qazvin (قزوین)",
    "Alvand (الوند)",
    "Mohammadiyeh (محمدیه)",
    "Takestan (تاکستان)",
    "Abyek (آبیک)",
    "Buin Zahra (بوئین‌زهرا)",
    "Eqbaliyeh (اقبالیه)",
    "Mahmoudabad Nemuneh (محمودآباد نمونه)",
  ],
  Zanjan: [
    "Zanjan (زنجان)",
    "Abhar (ابهر)",
    "Khorramdarreh (خرمدره)",
    "Qeydar (قیدار)",
    "Hidaj (هیدج)",
    "Saeen Qaleh (صائین‌قلعه)",
    "Tarom (طارم)",
    "Mahneshan (ماه‌نشان)",
  ],
  Yazd: [
    "Yazd (یزد)",
    "Meybod (میبد)",
    "Ardakan (اردکان)",
    "Bafq (بافق)",
    "Mehriz (مهریز)",
    "Abarkuh (ابرکوه)",
    "Taft (تفت)",
    "Ashkezar (اشکذر)",
    "Herat (هرات)",
    "Marvast (مروست)",
  ],
  Kerman: [
    "Kerman (کرمان)",
    "Sirjan (سیرجان)",
    "Rafsanjan (رفسنجان)",
    "Jiroft (جیرفت)",
    "Bam (بم)",
    "Zarand (زرند)",
    "Kahnuj (کهنوج)",
    "Shahr-e Babak (شهربابک)",
    "Bardsir (بردسیر)",
    "Baft (بافت)",
    "Anbarabad (عنبرآباد)",
    "Manujan (منوجان)",
  ],
  Hamadan: [
    "Hamadan (همدان)",
    "Malayer (ملایر)",
    "Nahavand (نهاوند)",
    "Tuyserkan (تویسرکان)",
    "Asadabad (اسدآباد)",
    "Bahar (بهار)",
    "Kabudarahang (کبودرآهنگ)",
    "Razan (رزن)",
    "Famenin (فامنین)",
  ],
  Lorestan: [
    "Khorramabad (خرم‌آباد)",
    "Borujerd (بروجرد)",
    "Dorud (دورود)",
    "Aligudarz (الیگودرز)",
    "Kuhdasht (کوهدشت)",
    "Nurabad (نورآباد)",
    "Pol-e Dokhtar (پلدختر)",
    "Azna (ازنا)",
    "Alashtar (الشتر)",
    "Sarableh (چغلوندی)",
  ],
  Golestan: [
    "Gorgan (گرگان)",
    "Gonbad-e Kavus (گنبد کاووس)",
    "Aliabad-e Katul (علی‌آباد کتول)",
    "Bandar Torkaman (بندر ترکمن)",
    "Azadshahr (آزادشهر)",
    "Kordkuy (کردکوی)",
    "Kalaleh (کلاله)",
    "Aq Qala (آق‌قلا)",
    "Minudasht (مینودشت)",
    "Galikash (گالیکش)",
    "Bandar Gaz (بندر گز)",
    "Gomishan (گمیشان)",
  ],
  Hormozgan: [
    "Bandar Abbas (بندرعباس)",
    "Qeshm (قشم)",
    "Kish (کیش)",
    "Minab (میناب)",
    "Bandar Lengeh (بندرلنگه)",
    "Roudan (رودان)",
    "Bastak (بستک)",
    "Hajiabad (حاجی‌آباد)",
    "Jask (جاسک)",
    "Parsian (پارسیان)",
    "Khamir (خمیر)",
  ],
  Bushehr: [
    "Bushehr (بوشهر)",
    "Borazjan (برازجان)",
    "Bandar Ganaveh (بندر گناوه)",
    "Bandar Kangan (بندر کنگان)",
    "Khormuj (خورموج)",
    "Bandar Dayyer (بندر دیر)",
    "Jam (جم)",
    "Asaluyeh (عسلویه)",
    "Bandar Deylam (بندر دیلم)",
    "Ahram (اهرم)",
  ],
  Ardabil: [
    "Ardabil (اردبیل)",
    "Parsabad (پارس‌آباد)",
    "Meshginshahr (مشگین‌شهر)",
    "Khalkhal (خلخال)",
    "Germi (گرمی)",
    "Bilesavar (بیله‌سوار)",
    "Namin (نمین)",
    "Sareyn (سرعین)",
    "Kowsar (کوثر)",
    "Aslanduz (اصلاندوز)",
  ],
  Kurdistan: [
    "Sanandaj (سنندج)",
    "Saqqez (سقز)",
    "Marivan (مریوان)",
    "Baneh (بانه)",
    "Qorveh (قروه)",
    "Bijar (بیجار)",
    "Kamyaran (کامیاران)",
    "Divandarreh (دیواندره)",
    "Dehgolan (دهگلان)",
    "Sarvabad (سروآباد)",
  ],
  "Sistan and Baluchestan": [
    "Zahedan (زاهدان)",
    "Zabol (زابل)",
    "Chabahar (چابهار)",
    "Iranshahr (ایرانشهر)",
    "Saravan (سراوان)",
    "Khash (خاش)",
    "Konarak (کنارک)",
    "Nik Shahr (نیک‌شهر)",
    "Mirjaveh (میرجاوه)",
    "Pishin (پیشین)",
    "Rasak (راسک)",
  ],
  Semnan: [
    "Semnan (سمنان)",
    "Shahrud (شاهرود)",
    "Damghan (دامغان)",
    "Garmsar (گرمسار)",
    "Mehdishahr (مهدی‌شهر)",
    "Eyvanki (ایوانکی)",
    "Sorkheh (سرخه)",
    "Aradan (آرادان)",
  ],
  "Chaharmahal and Bakhtiari": [
    "Shahrekord (شهرکرد)",
    "Borujen (بروجن)",
    "Lordegan (لردگان)",
    "Farokhshahr (فرخ‌شهر)",
    "Farsan (فارسان)",
    "Saman (سامان)",
    "Ben (بن)",
    "Ardal (اردل)",
    "Kiar (کیار)",
  ],
  "Kohgiluyeh and Boyer-Ahmad": [
    "Yasuj (یاسوج)",
    "Dogonbadan (دوگنبدان / گچساران)",
    "Dehdasht (دهدشت)",
    "Likak (لیکک)",
    "Charam (چرام)",
    "Basht (باشت)",
    "Landeh (لنده)",
    "Sisikht (سی‌سخت)",
  ],
  "North Khorasan": [
    "Bojnurd (بجنورد)",
    "Shirvan (شیروان)",
    "Esfarayen (اسفراین)",
    "Jajarm (جاجرم)",
    "Garmeh (گرمه)",
    "Maneh va Samalqan (مانه و سملقان)",
    "Faruj (فاروج)",
    "Raz va Jargalan (راز و جرگلان)",
  ],
  "South Khorasan": [
    "Birjand (بیرجند)",
    "Qaen (قائن)",
    "Ferdows (فردوس)",
    "Tabas (طبس)",
    "Boshruyeh (بشرویه)",
    "Sarayan (سرایان)",
    "Nehbandan (نهبندان)",
    "Darmian (درمیان)",
    "Sarbisheh (سربیشه)",
    "Khusf (خوسف)",
    "Zirkuh (زیرکوه)",
  ],
  Ilam: [
    "Ilam (ایلام)",
    "Dehloran (دهلران)",
    "Eyvan (ایوان)",
    "Abdanan (آبدانان)",
    "Mehran (مهران)",
    "Dareh Shahr (دره‌شهر)",
    "Sarableh (سرابله)",
    "Chardavol (چرداول)",
    "Malekshahi (ملکشاهی)",
    "Badreh (بدره)",
  ],
};
