# catalog/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import AuthorViewSet, BookViewSet

# Use DRF's DefaultRouter to generate list/detail URLs automatically
router = DefaultRouter()
router.register(r"books", BookViewSet, basename="book")
router.register(r"authors", AuthorViewSet, basename="author")

urlpatterns = [
    # Include all URLs generated by the router under the 'books/' and 'authors/' paths
    path("", include(router.urls)),
]
