# Generated by Django 5.2.6 on 2026-08-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly title format.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(max_length=17, unique=True, verbose_name="ISBN"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Cover Image URL",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("SCI_FI", "Science Fiction"),
                            ("HISTORY", "History"),
                            ("SCIENCE", "Science"),
                            ("TECH", "Technology"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Available as E-book"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(
                        default=False, verbose_name="Available as Audiobook"
                    ),
                ),
                (
                    "digital_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to EPUB/PDF file for licensed readers.",
                        max_length=500,
                        verbose_name="Digital File Path",
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to MP3/M4A file for licensed audio player.",
                        max_length=500,
                        verbose_name="Audio File Path",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="catalog.author",
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
                "unique_together": {("author", "title")},
            },
        ),
        migrations.CreateModel(
            name="BookFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("DIGITAL", "Digital"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=20,
                        verbose_name="Format Type",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="catalog.book",
                        verbose_name="Book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Format",
                "verbose_name_plural": "Book Formats",
                "ordering": ["book", "format_type"],
                "unique_together": {("book", "format_type")},
            },
        ),
    ]
