# Generated by Django 5.2.6 on 2026-09-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Genre Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Normalized Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Normalized Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Avatar URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Normalized Name'),
        ),
        migrations.AddField(
            model_name='author',
            name='primary_language',
            field=models.CharField(default='en', max_length=10, verbose_name='Primary Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('SCI_FI', 'Science Fiction'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('TECH', 'Technology'), ('BUSINESS', 'Business'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('PERSIAN_LIT', 'Persian Literature')], max_length=50, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.tag', verbose_name='Tags'),
        ),
    ]
