# Generated by Django 5.2.6 on 2026-08-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("DIGITAL", "Digital"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=20,
                        verbose_name="Format Type",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="catalog.book",
                        verbose_name="Book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Format",
                "verbose_name_plural": "Book Formats",
                "ordering": ["book", "format_type"],
                "unique_together": {("book", "format_type")},
            },
        ),
    ]
