# Generated by Django 5.2.6 on 2026-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_genre_tag_author_avatar_url_author_normalized_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content_tone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("philosophical", "Philosophical & Reflective"),
                    ("dystopian", "Dark & Dystopian"),
                    ("academic", "Analytical & Academic"),
                    ("inspiring", "Uplifting & Inspiring"),
                    ("humorous", "Lighthearted & Humorous"),
                    ("mystical", "Mystical & Spiritual"),
                ],
                default="philosophical",
                max_length=50,
                verbose_name="Content Tone",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="target_age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_ages", "All Ages"),
                    ("children", "Children (0-12)"),
                    ("young_adult", "Young Adult (13-17)"),
                    ("adult", "Adult (18+)"),
                ],
                default="all_ages",
                max_length=30,
                verbose_name="Target Age Group",
            ),
        ),
    ]
