# Generated by Django 5.2.6 on 2025-12-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_wishlistitem"),
        ("pricing", "0002_price_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address_line1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address Line 1"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Recipient Name"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_author_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Snapshot Author"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pricing.discountcode",
                verbose_name="Applied Discount",
            ),
        ),
    ]
