# Generated by Django 5.2.6 on 2026-08-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cartitem_unique_together_cartitem_book_format_and_more"),
        ("catalog", "0004_seed_book_formats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="book_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.bookformat",
                verbose_name="Book Format",
            ),
        ),
    ]
