# Generated by Django 5.2.6 on 2026-08-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_orderitem_book_format"),
        ("catalog", "0004_seed_book_formats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="book_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.bookformat",
                verbose_name="Book Format",
            ),
        ),
    ]
