# Generated by Django 5.2.6 on 2026-08-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_order_user"),
        ("catalog", "0002_alter_book_author"),
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licenses",
                to="catalog.book",
                verbose_name="Book",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses",
                to="cart.order",
                verbose_name="Source Order",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
