# Generated by Django 5.2.6 on 2026-08-19 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_orderitem_book_format"),
        ("catalog", "0004_seed_book_formats"),
        ("content", "0002_alter_license_book_alter_license_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="license",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="license",
            name="book_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licenses",
                to="catalog.bookformat",
                verbose_name="Book Format",
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                fields=("user", "book", "book_format"),
                name="unique_user_book_format_license",
            ),
        ),
    ]
