# Generated by Django 5.2.6 on 2026-08-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_seed_book_formats"),
        ("content", "0003_alter_license_unique_together_license_book_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="book_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licenses",
                to="catalog.bookformat",
                verbose_name="Book Format",
            ),
        ),
    ]
