# Generated by Django 5.2.6 on 2026-08-22 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Plan Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                ("tier", models.PositiveIntegerField(unique=True, verbose_name="Tier")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Monthly Price"
                    ),
                ),
                (
                    "digital_discount_percent",
                    models.IntegerField(default=0, verbose_name="Digital Discount %"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["tier"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                        max_length=10,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Discount Value"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("STORE", "Entire Store"),
                            ("BOOK", "Specific Book"),
                            ("AUTHOR", "Specific Author"),
                            ("GENRE", "Genre"),
                            ("FORMAT", "Book Format"),
                        ],
                        max_length=10,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=30, verbose_name="Genre"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIGITAL", "Digital"),
                            ("PHYSICAL", "Physical"),
                            ("AUDIO", "Audiobook"),
                        ],
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "activation",
                    models.CharField(
                        choices=[("AUTOMATIC", "Automatic"), ("COUPON", "Coupon")],
                        default="AUTOMATIC",
                        max_length=20,
                        verbose_name="Activation",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalog.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="pricing.discount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Price Value"
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="Minimum Price",
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Effective From"
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective Until"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "book_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.bookformat",
                        verbose_name="Book Format",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History Record",
                "verbose_name_plural": "Price History Records",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESERVED", "Reserved"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "auto_renew",
                    models.BooleanField(default=False, verbose_name="Auto Renew"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.subscriptionplan",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "ordering": ["-start_date"],
            },
        ),
    ]
