# Generated by Django 5.2.6 on 2026-07-26 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("pricing", "0002_price_min_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcode",
            options={},
        ),
        migrations.RemoveField(
            model_name="discountcode",
            name="discount_percent",
        ),
        migrations.RemoveField(
            model_name="discountcode",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="discountcode",
            name="valid_until",
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="max_uses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="times_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                        max_length=10,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discount Value"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("STORE", "Entire Store"),
                            ("BOOK", "Specific Book"),
                            ("AUTHOR", "Specific Author"),
                            ("GENRE", "Genre"),
                            ("FORMAT", "Book Format"),
                        ],
                        max_length=10,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=30, verbose_name="Genre"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIGITAL", "Digital"),
                            ("PHYSICAL", "Physical"),
                            ("AUDIO", "Audiobook"),
                        ],
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalog.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.AddField(
            model_name="discountcode",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codes",
                to="pricing.discount",
            ),
        ),
    ]
