# Generated by Django 5.2.6 on 2026-07-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_discountcode_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="activation",
            field=models.CharField(
                choices=[("AUTOMATIC", "Automatic"), ("COUPON", "Coupon")],
                default="AUTOMATIC",
                max_length=20,
                verbose_name="Activation",
            ),
        ),
    ]
