# Generated by Django 5.2.6 on 2026-08-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_discount_activation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codes",
                to="pricing.discount",
            ),
        ),
    ]
