# Generated by Django 5.2.6 on 2026-08-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_seed_book_formats"),
        ("pricing", "0005_alter_discountcode_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="book_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="catalog.bookformat",
                verbose_name="Book Format",
            ),
        ),
    ]
