# Generated by Django 5.2.6 on 2026-08-19 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_migrate_prices_to_formats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersubscription",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
            },
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="is_active",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="auto_renew",
            field=models.BooleanField(default=False, verbose_name="Auto Renew"),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RESERVED", "Reserved"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
