# Generated by Django 5.2.6 on 2026-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0008_alter_usersubscription_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="end_date",
            field=models.DateTimeField(verbose_name="End Date"),
        ),
    ]
