# Generated by Django 5.2.6 on 2026-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0009_alter_usersubscription_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ["tier"],
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Tier"
            ),
        ),
    ]
