# Generated by Django 5.2.6 on 2026-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0010_alter_subscriptionplan_options_subscriptionplan_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="tier",
            field=models.PositiveIntegerField(unique=True, verbose_name="Tier"),
        ),
    ]
