# Generated by Django 5.2.6 on 2026-08-22 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("BOOK_CREATE", "Book Creation"),
                            ("BOOK_UPDATE", "Book Update"),
                            ("BOOK_DELETE", "Book Deletion"),
                            ("AUTHOR_CREATE", "Author Creation"),
                            ("AUTHOR_UPDATE", "Author Update"),
                            ("PRICE_CHANGE", "Price Change"),
                        ],
                        max_length=30,
                        verbose_name="Proposal Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("APPLIED", "Applied"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Applied At"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrator who reviewed this proposal.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Publisher member who submitted this proposal.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="publishing.publisher",
                        verbose_name="Publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceChangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Price"
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Minimum Price",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_change_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Change Proposal",
                "verbose_name_plural": "Price Change Proposals",
                "ordering": ["-proposal__created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookUpdateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Cover Image URL",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("SCI_FI", "Science Fiction"),
                            ("HISTORY", "History"),
                            ("SCIENCE", "Science"),
                            ("TECH", "Technology"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Available as E-book"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(
                        default=False, verbose_name="Available as Audiobook"
                    ),
                ),
                (
                    "digital_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Digital File Path"
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Audio File Path"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_update",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Update Proposal",
                "verbose_name_plural": "Book Update Proposals",
            },
        ),
        migrations.CreateModel(
            name="BookDeleteProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_delete",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Deletion Proposal",
                "verbose_name_plural": "Book Deletion Proposals",
            },
        ),
        migrations.CreateModel(
            name="BookCreateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Cover Image URL",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("SCI_FI", "Science Fiction"),
                            ("HISTORY", "History"),
                            ("SCIENCE", "Science"),
                            ("TECH", "Technology"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Available as E-book"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(
                        default=False, verbose_name="Available as Audiobook"
                    ),
                ),
                (
                    "digital_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Digital File Path"
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Audio File Path"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(db_index=True, max_length=17, verbose_name="ISBN"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_creation_proposals",
                        to="catalog.author",
                    ),
                ),
                (
                    "created_book",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creation_proposal",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_create",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Creation Proposal",
                "verbose_name_plural": "Book Creation Proposals",
            },
        ),
        migrations.CreateModel(
            name="AuthorUpdateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_proposals",
                        to="catalog.author",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_update",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Update Proposal",
                "verbose_name_plural": "Author Update Proposals",
            },
        ),
        migrations.CreateModel(
            name="AuthorCreateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_create",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Creation Proposal",
                "verbose_name_plural": "Author Creation Proposals",
            },
        ),
        migrations.CreateModel(
            name="PublisherMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("EDITOR", "Editor"),
                        ],
                        default="EDITOR",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="publishing.publisher",
                        verbose_name="Publisher",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publisher Membership",
                "verbose_name_plural": "Publisher Memberships",
                "ordering": ["publisher", "user__username"],
            },
        ),
    ]
