# Generated by Django 5.2.6 on 2026-08-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="submitted_by",
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
        migrations.DeleteModel(
            name="Proposal",
        ),
    ]
