# Generated by Django 5.2.6 on 2026-09-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcreateproposal',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('SCI_FI', 'Science Fiction'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('TECH', 'Technology'), ('BUSINESS', 'Business'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('PERSIAN_LIT', 'Persian Literature')], max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='bookupdateproposal',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('SCI_FI', 'Science Fiction'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('TECH', 'Technology'), ('BUSINESS', 'Business'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('PERSIAN_LIT', 'Persian Literature')], max_length=50, verbose_name='Genre'),
        ),
    ]
