# Generated by Django 5.2.6 on 2026-08-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_author"),
        ("publishing", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorCreateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_create",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Creation Proposal",
                "verbose_name_plural": "Author Creation Proposals",
            },
        ),
        migrations.CreateModel(
            name="AuthorUpdateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_proposals",
                        to="catalog.author",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_update",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Update Proposal",
                "verbose_name_plural": "Author Update Proposals",
            },
        ),
        migrations.CreateModel(
            name="BookCreateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="Cover Image URL"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("SCI_FI", "Science Fiction"),
                            ("HISTORY", "History"),
                            ("SCIENCE", "Science"),
                            ("TECH", "Technology"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Available as E-book"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(
                        default=False, verbose_name="Available as Audiobook"
                    ),
                ),
                (
                    "digital_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Digital File Path"
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Audio File Path"
                    ),
                ),
                ("isbn", models.CharField(max_length=17, verbose_name="ISBN")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_creation_proposals",
                        to="catalog.author",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_create",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Creation Proposal",
                "verbose_name_plural": "Book Creation Proposals",
            },
        ),
        migrations.CreateModel(
            name="BookDeleteProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_delete",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Deletion Proposal",
                "verbose_name_plural": "Book Deletion Proposals",
            },
        ),
        migrations.CreateModel(
            name="BookUpdateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="Cover Image URL"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("SCI_FI", "Science Fiction"),
                            ("HISTORY", "History"),
                            ("SCIENCE", "Science"),
                            ("TECH", "Technology"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, verbose_name="Available as E-book"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(
                        default=False, verbose_name="Available as Audiobook"
                    ),
                ),
                (
                    "digital_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Digital File Path"
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Audio File Path"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="update_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_update",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Update Proposal",
                "verbose_name_plural": "Book Update Proposals",
            },
        ),
        migrations.CreateModel(
            name="PriceChangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Price",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_change_proposals",
                        to="catalog.book",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change",
                        to="publishing.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Change Proposal",
                "verbose_name_plural": "Price Change Proposals",
            },
        ),
    ]
