# Generated by Django 5.2.6 on 2026-08-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0004_authorcreateproposal_authorupdateproposal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrator who reviewed this proposal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="submitted_by",
            field=models.ForeignKey(
                help_text="Publisher member who submitted this proposal.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_proposals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted By",
            ),
        ),
        migrations.CreateModel(
            name="PublisherMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("EDITOR", "Editor"),
                        ],
                        default="EDITOR",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="publishing.publisher",
                        verbose_name="Publisher",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publisher Membership",
                "verbose_name_plural": "Publisher Memberships",
                "ordering": ["publisher", "user__username"],
            },
        ),
    ]
