# Generated by Django 5.2.6 on 2026-08-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_author"),
        ("publishing", "0005_alter_proposal_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcreateproposal",
            name="created_book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creation_proposal",
                to="catalog.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookcreateproposal",
            name="cover_image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Cover Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="bookupdateproposal",
            name="cover_image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Cover Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPLIED", "Applied"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
