# Generated by Django 5.2.6 on 2026-08-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0006_bookcreateproposal_created_book_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricechangeproposal",
            options={
                "ordering": ["-proposal__created_at"],
                "verbose_name": "Price Change Proposal",
                "verbose_name_plural": "Price Change Proposals",
            },
        ),
        migrations.AlterField(
            model_name="bookcreateproposal",
            name="isbn",
            field=models.CharField(db_index=True, max_length=17, verbose_name="ISBN"),
        ),
    ]
