# Generated by Django 5.2.6 on 2026-08-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0007_alter_pricechangeproposal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("APPLIED", "Applied"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
