# Generated by Django 5.2.6 on 2026-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.CharField(default="Wallet charge", max_length=255),
        ),
    ]
