# Generated by Django 5.2.6 on 2026-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="authority",
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="res_num",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
